### ISSUE TITLE
VSecM shall automatically generate secrets given a template

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#167]
Carvel suite has a secret controller that does something similar.

```
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-password
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: long-user-password
spec:
  length: 124
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgresql-password
spec:
  secretTemplate:
    type: Opaque
    stringData:
      postgresql-password: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: complex-password
spec:
  length: 27
  digits: 2
  uppercaseLetters: 4
  lowercaseLetters: 10
  symbols: 3
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: symbol-only-password
spec:
  length: 7
  symbols: 7
  symbolCharSet: "!$#%"
---
```

On that line of thought, VSecM can do somehting similar too.

The potential uses cases for this will be limited, but maybe people can get creative and figure out other options too.

When provided a spec, **VSecM Safe** can generate an assign a random secrets based on the spec.

This can be useful if two parties need to share the same secret, nobody else has to know the secret, and a more established technology like mTLS is not an option for a variety of reasons.

Or, for example, the secrets are used to generate credentials elsewhere (a username and password for a database that is totally randomly created — since no human knows the secret, no human can use the db credentials -- again, a certificate authentication would be a better option instead, but might not be possible for a variety of reasons)

As a bonus, we can use the `-e` flag to just create (but not assign) the secret.
