### ISSUE TITLE
Sentinel and Safe’s Identity.yaml need stricter matchers

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#190]
What we have:

```yaml
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: vsecm-safe
spec:
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/vsecm-safe\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vsecm-safe
      app.kubernetes.io/part-of: vsecm-system
  workloadSelectorTemplates:
  - "k8s:ns:{{ .PodMeta.Namespace }}"
  - "k8s:sa:{{ .PodSpec.ServiceAccountName }}"
```

what we need:

```yaml
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: vsecm-safe
spec:
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/vsecm-safe\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vsecm-safe
      app.kubernetes.io/part-of: vsecm-system
  workloadSelectorTemplates:
  - "k8s:ns:vsecm-system"
  - "k8s:sa:vsecm-safe"
```

same for Sentinel too. the `workloadSelectorTemplates` section needs to change.
