### ISSUE TITLE
demo autoscaling use case

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#224]
```
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
```

Note that, for this to work we need to define how the system behaves in autoscaled mode.

Either leader election, or using a common backing store and using some lock etc.

There are already issues for that. so to start this demo we should at least have an “auto scaling” user story sorted out.
