### ISSUE TITLE
SPIRE Controller Manager v4.x failed to work with the current version of SPIRE and VSecM

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#365]
Here’s the current versions of dependencies that pass the integration tests:

```
  images:
    safe:
      distrolessRepository: vsecm-ist-safe
      distrolessFipsRepository: vsecm-ist-fips-safe
      photonRepository: vsecm-photon-safe
      photonFipsRepository: vsecm-photon-fips-safe
      tag: 0.21.5
      pullPolicy: IfNotPresent
    sentinel:
      distrolessRepository: vsecm-ist-sentinel
      distrolessFipsRepository: vsecm-ist-fips-sentinel
      photonRepository: vsecm-photon-sentinel
      photonFipsRepository: vsecm-photon-fips-sentinel
      tag: 0.21.5
      pullPolicy: IfNotPresent
    spireAgent:
      repository: ghcr.io/spiffe/spire-agent
      tag: 1.8.6
      pullPolicy: IfNotPresent
    spiffeCsiDriver:
      repository: ghcr.io/spiffe/spiffe-csi-driver
      tag: 0.2.4
      pullPolicy: IfNotPresent
    nodeDriverRegistrar:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.9.2
      pullPolicy: IfNotPresent
    spireServer:
      repository: ghcr.io/spiffe/spire-server
      tag: 1.8.6
      pullPolicy: IfNotPresent
    spireControllerManager:
      repository: ghcr.io/spiffe/spire-controller-manager
      tag: 0.3.0
      pullPolicy: IfNotPresent
```

When we change `spireControllerManager` to `0.4.x` and update relevant CRDs, VSecM Safe fails to retrieve SVIDs from the workload API; and when we run `make test-local` the tests fail.
