### ISSUE TITLE
update-k8s-manifests uses vsecm instead of localhost:5000 for local images

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#380]
Following the documentation and executing `./hack/update-k8s-manifests.sh 0.21.6` to generate new manifests.

expectation:
* local manifests shall have `localhost:5000` as their registry.

what happens:
* we see `image: "vsecm/…"` instead.

example snippet from a generated file:

```
      containers:
        - name: main
          image: "vsecm/vsecm-ist-safe:0.21.6"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
```

Either documentation is incorrect and we need to add a parameter (or maybe use `make` and also update the doc accordingly too), or there is a problem with the generator.
