### ISSUE TITLE
spire server has nodeport; it shouldn’t — have the option to override it for production setup

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#627]

**Comment by v0lkan** [comment]
Maybe try to do two things to save time:

* let it use `CluserIP` 
* and also let is use a persistent volume

(both from helm chart configuration)

**Comment by v0lkan** [comment]
this should be the default:

```
## @param service.type Type of the Spire server service created
## @param service.port Port for the created service
## @param service.annotations [object] Annotations to add to the service object
##
service:
  type: ClusterIP
  port: 8081
  annotations: {}
```

**Comment by v0lkan** [comment]
While we are at there, it’s good to add these to where it matters:

```
## @param persistence.type What type of volume to use for persistence. Valid options pvc (recommended), hostPath, emptyDir (testing only)
## @param persistence.size What type of volume to use for persistence. Valid options pvc (recommended), hostPath, emptyDir (testing only)
## @param persistence.accessMode What type of volume to use for persistence. Valid options pvc (recommended), hostPath, emptyDir (testing only)
## @param persistence.storageClass What type of volume to use for persistence. Valid options pvc (recommended), hostPath, emptyDir (testing only)
## @param persistence.hostPath Which path to use on the host when type = hostPath
##
persistence:
  type: pvc
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: null
  hostPath: ""
```

not only spire-server but also vsecm components too.
