### ISSUE TITLE
a kubernetes admission controller that validates vsecm-related clusterspiffeids

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#734]
Given this id:

```
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: example
spec:
  # SPIFFE ID `MUST` start with "spiffe://vsecm.com/workload/$workloadName/ns/"
  # for `vsecm-safe` to recognize the workload and dispatch secrets to it.
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/example\
    /ns/default\
    /sa/example\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: example
  workloadSelectorTemplates:
  - "k8s:ns:default"
  - "k8s:sa:example"
  ```

The controller will ensure that `ns/default/sa/example` matches the ns and as selectors of the workloadselectortemplate

`app.kubernetes.io/name: example` matches the name given in `workload/example`

`{{ .PodMeta.Name }}` is literally written as is.

This will ensure that the namespace and service account in the cluster spiffe id matches the workload selector;
and the name part of the clusterspiffe id comes from the actual pod meta and it’s not forged.
