### ISSUE TITLE
Create a ClusterVSecMID Custom resource

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#95]
```
apiVersion: aegis.z2h.dev/v1alpha1
kind: AegisID
metadata:
  name: aegis-workload-demo
spec:
  workloadName: aegis-workload-demo
  workloadNamespace: <optional | default>
  workloadServiceAccoount: <optional | default >
  workloadTrustDomain: <optional | aegis.z2h.dev >
```

see discussion here: https://github.com/shieldworks/aegis/issues/188
